name: specter_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter: 
    sdk: flutter
  specter_rust: 
    path: ./specter_rust

  get: 4.3.8
  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0
  qr_flutter: ^4.0.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/face_id.svg
    - assets/icons/fingerprint.svg
    - assets/icons/delete.svg
    - assets/icons/vpn_key.svg
    - assets/icons/account_balance_wallet.svg
    - assets/icons/qr_code_scanner.svg
    - assets/icons/coolicon.svg
    - assets/icons/bitcoin.svg
    - assets/icons/account_tree.svg
    - assets/icons/top_right_icon.svg
    - assets/icons/edit.svg
    - assets/icons/content_copy.svg
    - assets/icons/globe_1.svg
    - assets/icons/chevron_right.svg
    - assets/stickers/key-x512.png
    - assets/stickers/ghost_char-x512.png
    - assets/stickers/ghost_normal_3d-x512.png
    - assets/stickers/bitcoin-1.png
    - assets/stickers/bitcoin-2.png
    - assets/stickers/bitcoin-3.png

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/static/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish/static/Mulish-Italic.ttf
          style: italic
        - asset: assets/fonts/Mulish/static/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish/static/Mulish-Bold.ttf
          weight: 700
